name = "LyceumRegistry"
uuid = "96ca1a0e-015d-46b7-a12d-07d1320642ca"
repo = "https://github.com/Lyceum/LyceumRegistry.git"

[packages]
175de200-b73b-11e9-28b7-9b5b306cec37 = { name = "Shapes", path = "S/Shapes" }
32af7c3b-80ec-5621-8194-2f6cb2280831 = { name = "MuJoCo_jll", path = "M/MuJoCo_jll" }
48b9757e-04b8-4dbf-b6ed-75c13d9e4026 = { name = "LyceumMuJoCo", path = "L/LyceumMuJoCo" }
5c5e3362-9445-4819-9f95-51c44c51adeb = { name = "UniversalLogger", path = "U/UniversalLogger" }
6917c76a-ac01-4302-a33e-8c456ab70f71 = { name = "LyceumAI", path = "L/LyceumAI" }
93189219-7048-461c-94ec-443a161ed927 = { name = "MuJoCo", path = "M/MuJoCo" }
a1178c53-d320-4ec4-b60e-765dae4c6b59 = { name = "LyceumViz", path = "L/LyceumViz" }
c0099f9a-b73b-11e9-1fa7-371fe55f427b = { name = "DevTools", path = "D/DevTools" }
db31fed1-ca1e-4084-8a49-12fae1996a55 = { name = "LyceumBase", path = "L/LyceumBase" }
